backend:
  name: github
  repo: michaelord/cms
  branch: main
  auth_scope: repo

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "uuid" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Slug", name: "slug", widget: "string" }
      - {
          name: "author",
          label: "Author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "id",
          display_fields: ["name"]
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "authors"
    label: "Authors"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "id", label: "ID", widget: "uuid" }
      - { name: "name", label: "Name", widget: "string" }
      - { name: "bio", label: "Bio", widget: "text", required: false }
      - { name: "avatar", label: "Avatar", widget: "image", required: false }

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "id", label: "ID", widget: "uuid" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "author",
          label: "Author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "id",
          display_fields: ["name"]
        }
      - { name: "body", label: "Body", widget: "markdown" }
